module.exports = { other:
{ viewport: 'width=device-width, initial-scale=1',
  title: 'The Domain Name System (DNS) is the backbone of the internet. Here’s how it all works.',
  canonical: 'https://medium.freecodecamp.com/the-domain-name-system-dns-is-the-backbone-of-the-internet-heres-how-it-all-works-5706d0afa0fa',
  referrer: 'unsafe-url',
  description: 'Ultimately by understanding how DNS works, referred to as the backbone of the internet. You can become involved and shape the internet. How this works is a common interview question for devs.',
  themeColor: '#000000',
  fbAppId: '542599432471018',
  publisher: 'https://plus.google.com/103654360130207659246',
  author: 'Nikolas O\'Donnell',
  articlePublisher: 'https://www.facebook.com/freecodecamp',
  articleAuthor: 'https://medium.freecodecamp.com/@nikodonnell',
  fbSmartPublishRobots: 'noauto',
  robots: 'index, follow',
  articlePublishedTime: '2017-04-26T19:29:33.569Z',
  alIosAppName: 'Medium',
  alIosAppStoreId: '828256236',
  alAndroidPackage: 'com.medium.reader',
  alAndroidAppName: 'Medium',
  alIosUrl: 'medium://p/5706d0afa0fa',
  alAndroidUrl: 'medium://p/5706d0afa0fa',
  alWebUrl: 'https://medium.freecodecamp.com/the-domain-name-system-dns-is-the-backbone-of-the-internet-heres-how-it-all-works-5706d0afa0fa',
  search: '/osd.xml',
  alternate: 'android-app://com.medium.reader/https/medium.com/p/5706d0afa0fa',
  stylesheet: 'https://cdn-static-1.medium.com/_/fp/css/main-base.wLWeXlP78AnAuaRbND_w3g.css',
  icon: 'https://cdn-static-1.medium.com/_/fp/icons/favicon-medium.TAS6uQ-Y7kcKgi0xjcYHXw.ico',
  appleTouchIcon: 'https://cdn-images-1.medium.com/fit/c/60/60/1*MotlWcSa2n6FrOx3ul89kw.png',
  maskIcon: 'https://cdn-static-1.medium.com/_/fp/icons/favicon.KjTfUJo7yJH_fCoUzzH3cg.svg' },
  ogp:
  { ogTitle: 'The Domain Name System (DNS) is the backbone of the internet. Here’s how it all works.',
    ogUrl: 'https://medium.freecodecamp.com/the-domain-name-system-dns-is-the-backbone-of-the-internet-heres-how-it-all-works-5706d0afa0fa',
    ogImage: [ { url: 'https://cdn-images-1.medium.com/max/1200/1*_aojoKJJSZRCADzj9N06uA.jpeg' } ],
    ogDescription: 'Ultimately by understanding how DNS works, referred to as the backbone of the internet. You can become involved and shape the internet.',
    ogType: 'article',
    ogSiteName: 'freeCodeCamp' },
  twitter:
  { twitterDescription: 'Ultimately by understanding how DNS works, referred to as the backbone of the internet. You can become involved and shape the internet.',
    twitterImage: [ { src: 'https://cdn-images-1.medium.com/max/1200/1*_aojoKJJSZRCADzj9N06uA.jpeg' } ],
    twitterCard: 'summary_large_image',
    twitterSite: '@freecodecamp',
    twitterLabel1: 'Reading time',
    twitterData1: '8 min read',
    twitterAppNameIphone: 'Medium',
    twitterAppIdIphone: '828256236',
    twitterAppUrlIphone: 'medium://p/5706d0afa0fa' } }
