name: test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*.*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*", "current"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm test
